<?php

function isLoggedFC(){
    if(isset($_COOKIE['fcsid'])){
        if(isset(json_decode(FC_ApiUserMe($_COOKIE['fcsid']))->code)){
            return false;
        } else return true;
    }
    else return false;
}



function fbStartLogin($phone){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://graph.accountkit.com/v1.3/start_login');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "credentials_type=phone_number&access_token=AA%7C1581054295289832%7C28ac0a21b17a7cfd420c096f361fbeee&fields=terms_of_service%2Cprivacy_policy&locale=ru_RU&phone_number={$phone}&sdk=android&fb_app_events_enabled=true&response_type=code&");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; unknown Build/LMY48Z) AccountKitAndroidSDK/4.37.0';
    $headers[] = 'Host: graph.accountkit.com';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
return $result;
}


function fbConfirmLogin($phone, $code, $request_code){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://graph.accountkit.com/v1.3/confirm_login');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, "credentials_type=phone_number&access_token=AA%7C1581054295289832%7C28ac0a21b17a7cfd420c096f361fbeee&locale=ru_RU&phone_number={$phone}&sdk=android&confirmation_code={$code}&fb_app_events_enabled=true&login_request_code={$request_code}");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; unknown Build/LMY48Z) AccountKitAndroidSDK/4.37.0';
    $headers[] = 'Host: graph.accountkit.com';
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}


function FC_Auth($code){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/auth/kit?code='.$code);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}


function FC_ApiUserMe($token){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/user/me');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Session-Id: -7467387597710353860';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}


function FC_ApiUser($id,$token){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/user/'.$id);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Session-Id: -229363973835437277';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiFeed($token, $time = 0,$from = 0){
    //$time = ($time == 0) ? time():$time;
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/feed?lat=0.0&long=0.0&from='.$from.'&count=32&last_ts='.$time);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Session-Id: 7383512435278215160';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiChatsAll($token,$from = 0){
    //$time = ($time == 0) ? time():$time;
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat?from='.$from.'&count=32');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Session-Id: 7383512435278215160';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiChat($chat_id, $token, $time, $reverse=false){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat/'.$chat_id.'/message?follow='.$reverse.'&from='.$time.'743715618&count=100&reverse=false');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Session-Id: 7383512435278215160';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiChatInfo($chat_id, $token){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat/'.$chat_id.'/info?follow=false&from=&count=1');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Session-Id: 7383512435278215160';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiSend($chat_id, $token, $msg){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
$random = mt_rand(11111111,999999999999);
    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat/'.$chat_id.'/message?random_id='.$random.'&cat=0');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(['text'=>$msg]));
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Session-Id: 7383512435278215160';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Content-Type: application/json; charset=utf-8';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}


function FC_ApiSendSticker($chat_id, $token, $sticker_id){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    $random = mt_rand(11111111,999999999999);
    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat/'.$chat_id.'/message?random_id='.$random.'&cat=0');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, '{"text":"","sticker":'.$sticker_id.'}');
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'Session-Id: 7383512435278215160';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Content-Type: application/json; charset=utf-8';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}


function FC_ApiRead($chat_id, $token){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat/'.$chat_id.'/unread');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Session-Id: -229363973835437277';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}


function FC_ApiNewChat($cat,$name,$sticker,$cover,$bg,$token){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $postarr = array();
    if($cat != '')
        $postarr['cat'] = $cat;
    if($cover !== '')
        $postarr['cover'] = $cover;
    if($bg != ''){
        $postarr['bg'] = $bg;
    }
    if($sticker != ''){
        $postarr['sticker'] = $sticker;
    }
    $postarr['name'] = $name;
    $postarr['lat'] = 0.0;
    $postarr['long'] = 0.0;
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postarr));
 //   curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"cat\":1,\"cover\":\"481dde9ef1d\",\"lat\":0.0,\"long\":0.0,\"name\":\"cat\"}");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Session-Id: -229363973835437277';
    $headers[] = 'Content-Type: application/json; charset=utf-8';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiSaveProfile($name, $bio, $layers, $token){
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/user/me');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(['bio'=>$bio,'layers'=>$layers,'name'=>$name]));
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Session-Id: -229363973835437277';
    $headers[] = 'Content-Type: application/json; charset=utf-8';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
    return $result;
}

function FC_ApiChatCover($token){
    // initialise the curl request
// устанавливаем соединение с сервером
$fp = fsockopen('face.cat', 80, $errno, $errstr, 30);
if (!$fp) die($errstr.' ('.$errno.')');

$file = 'images/tmp.jpg';
// содержимое файла
$content = file_get_contents($file);

// разделитель
$boundary = 'c2a1720b-3915-4dc2-9eab-d04585ceeb18';//md5(uniqid(time()));


$body = '--'.$boundary."\r\n";
$body = $body.'Content-Disposition: form-data; name="photo"; filename="photo.jpg"'."\r\n";
$body = $body.'Content-Type: image/jpg'."\r\n";
$body = $body.'Content-Transfer-Encoding: binary'."\r\n\r\n";
$body = $body.$content."\r\n";

$body = $body.'--'.$boundary.'--';

// пишем в сокет метод, URI и протокол
fwrite($fp, 'POST /api/chat/cover HTTP/1.1'."\r\n");
// а также имя хоста
fwrite($fp, 'Host: face.cat'."\r\n");
// отправляем заголовки
fwrite($fp, 'Content-Type: multipart/form-data; boundary='.$boundary."\r\n");

fwrite($fp, "Accept: application/json\r\n");
fwrite($fp, "Session-Id: -229363973835437277\r\n");
    fwrite($fp, "User-Agent: 1 Android/-1 ru unknown\r\n");
    fwrite($fp, "X-Token: ".$token."\r\n");
fwrite($fp, 'Content-Length: '.strlen($body)."\r\n\r\n");
// теперь передаем данные
fwrite($fp, $body);

// получаем ответ
$result = '';
while ( !feof($fp) ) $result .= fgets($fp, 1024);
// закрываем соединение
fclose($fp);
// выводим ответ в браузер
    echo $result;
//return $result;
}

function FC_ApiChatPhoto($chat_id,$token){
    // initialise the curl request
// устанавливаем соединение с сервером
    $fp = fsockopen('face.cat', 80, $errno, $errstr, 30);
    if (!$fp) die($errstr.' ('.$errno.')');

    $file = 'images/tmp.jpg';
// содержимое файла
    $content = file_get_contents($file);

// разделитель
    $boundary = 'c2a1720b-3915-4dc2-9eab-d04585ceeb18';//md5(uniqid(time()));


    $body = '--'.$boundary."\r\n";
    $body = $body.'Content-Disposition: form-data; name="photo"; filename="photo.jpg"'."\r\n";
    $body = $body.'Content-Type: image/jpg'."\r\n";
    $body = $body.'Content-Transfer-Encoding: binary'."\r\n\r\n";
    $body = $body.$content."\r\n";

    $body = $body.'--'.$boundary.'--';

// пишем в сокет метод, URI и протокол
    fwrite($fp, 'POST /api/chat/'.$chat_id.'/photo HTTP/1.1'."\r\n");
// а также имя хоста
    fwrite($fp, 'Host: face.cat'."\r\n");
// отправляем заголовки
    fwrite($fp, 'Content-Type: multipart/form-data; boundary='.$boundary."\r\n");

    fwrite($fp, "Accept: application/json\r\n");
    fwrite($fp, "Session-Id: -229363973835437277\r\n");
    fwrite($fp, "User-Agent: 1 Android/-1 ru unknown\r\n");
    fwrite($fp, "X-Token: ".$token."\r\n");
    fwrite($fp, 'Content-Length: '.strlen($body)."\r\n\r\n");
// теперь передаем данные
    fwrite($fp, $body);

// получаем ответ
    $result = '';
    while ( !feof($fp) ) $result .= fgets($fp, 1024);
// закрываем соединение
    fclose($fp);
// выводим ответ в браузер
  echo $result;
//return $result;
}


function FC_ApiTyping($chat_id, $token){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, 'https://face.cat/api/chat/'.$chat_id.'/typing');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

    curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Accept: application/json';
    $headers[] = 'User-Agent: 1 Android/-1 ru unknown';
    $headers[] = 'X-Token: '.$token;
    $headers[] = 'Session-Id: -229363973835437277';
    $headers[] = 'Host: face.cat';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close ($ch);
}
